import {
  DEFAULT_THINKING,
  ENDPOINTS,
  RATE_LIMIT_BACKOFF_MS,
  RATE_LIMIT_RETRIES,
  SESSION_HEADER,
  type ThinkingMode,
} from './config';
import { InceptionError, isAbortError, toInceptionError } from './errors';
import { parseStreamPayload, type StreamEvent } from './events';
import { challengeError, httpError, isChallengeResponse, sleep, type FetchLike } from './http';
import { buildChatBody, toWireMessages, type ChatTurn } from './messages';
import type { SessionManager } from './session';
import { SSEDecoder } from './sse';

export interface ChatOptions {
  /** Conversation id (the web app sends one per chat). */
  chatId: string;
  /** Full history, ending with the new user turn. */
  turns: readonly ChatTurn[];
  thinking?: ThinkingMode;
  webSearch?: boolean;
  /** Optional custom instructions, prepended to the first user turn. */
  system?: string;
  timezone?: string;
  signal?: AbortSignal;
}

export interface RetryInfo {
  reason: 'rate-limit' | 'auth';
  attempt: number;
  delayMs: number;
}

export interface ClientOptions {
  baseUrl: string;
  session: SessionManager;
  /** Returns the current transport; read on every request so it can be swapped live. */
  getFetch: () => FetchLike;
  onRetry?: (info: RetryInfo) => void;
  /** Base delay for 429 retries (the web app uses 1.5 s, then 3 s). */
  rateLimitBackoffMs?: number;
}

/**
 * Talks to chat.inceptionlabs.ai the way its own web app does, from whatever
 * browser context runs it. No proxy, no server of our own.
 */
export class InceptionClient {
  private readonly baseUrl: string;

  constructor(private readonly options: ClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/+$/, '');
  }

  /**
   * Send the conversation and stream the answer as typed events.
   *
   * Retries, in the same spirit as the web app: 429 → wait 1.5 s, 3 s and try again;
   * 401/403 → re-create the session once and try again. A bot checkpoint throws
   * `InceptionError('challenge')` so the UI can let the browser pass it.
   */
  async *chat(options: ChatOptions): AsyncGenerator<StreamEvent, void, undefined> {
    const { signal } = options;
    const messages = toWireMessages(options.turns, options.system);
    const last = messages[messages.length - 1];
    if (!last || last.role !== 'user') {
      throw new InceptionError('protocol', 'There is no user message to send.');
    }
    const body = JSON.stringify(
      buildChatBody({
        chatId: options.chatId,
        messages,
        thinking: options.thinking ?? DEFAULT_THINKING,
        webSearch: options.webSearch ?? true,
        timezone: options.timezone,
      }),
    );

    let rateRetries = 0;
    let authRetried = false;
    for (;;) {
      throwIfAborted(signal);
      const token = await this.options.session.ensure();
      throwIfAborted(signal);
      const res = await this.post(ENDPOINTS.chat, body, token, signal);

      if (await isChallengeResponse(res)) {
        discard(res);
        throw challengeError();
      }
      if (res.status === 429 && rateRetries < RATE_LIMIT_RETRIES) {
        rateRetries++;
        const delayMs = (this.options.rateLimitBackoffMs ?? RATE_LIMIT_BACKOFF_MS) * rateRetries;
        discard(res);
        this.options.onRetry?.({ reason: 'rate-limit', attempt: rateRetries, delayMs });
        await sleep(delayMs, signal);
        continue;
      }
      if ((res.status === 401 || res.status === 403) && !authRetried) {
        authRetried = true;
        discard(res);
        this.options.session.invalidate();
        this.options.onRetry?.({ reason: 'auth', attempt: 1, delayMs: 0 });
        continue;
      }
      if (!res.ok) throw await httpError(res, 'The chat request');
      if (!res.body) throw new InceptionError('protocol', 'The server returned an empty response.');

      yield* readEventStream(res.body, signal);
      return;
    }
  }

  /**
   * Suggested follow-up questions, generated by the server for the finished exchange
   * (the web app calls this after every answer). Returns [] on any failure.
   */
  async followUps(turns: readonly ChatTurn[], signal?: AbortSignal): Promise<string[]> {
    try {
      const messages = toWireMessages(turns).map(({ role, parts }) => ({ role, parts }));
      if (messages.length < 2) return [];
      const token = await this.options.session.ensure();
      const res = await this.post(ENDPOINTS.followUps, JSON.stringify({ messages }), token, signal);
      if (!res.ok) {
        discard(res);
        return [];
      }
      const json = (await res.json()) as { follow_ups?: unknown };
      if (!Array.isArray(json.follow_ups)) return [];
      return json.follow_ups
        .filter((s): s is string => typeof s === 'string' && s.trim().length > 0)
        .map((s) => s.trim())
        .slice(0, 5);
    } catch {
      return [];
    }
  }

  private async post(path: string, body: string, token: string, signal?: AbortSignal): Promise<Response> {
    try {
      return await this.options.getFetch()(this.baseUrl + path, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', [SESSION_HEADER]: token },
        body,
        credentials: 'include',
        signal,
      });
    } catch (error) {
      if (signal?.aborted || isAbortError(error)) throw new InceptionError('aborted', 'Request cancelled.', { cause: error });
      const err = toInceptionError(error, 'network');
      throw new InceptionError('network', `Could not reach ${hostOf(this.baseUrl)}.`, { cause: error, detail: err.message });
    }
  }
}

/**
 * Decode a UI-message SSE stream into typed events. UTF-8 is decoded in streaming
 * mode so characters split across network chunks survive intact.
 */
export async function* readEventStream(
  body: ReadableStream<Uint8Array>,
  signal?: AbortSignal,
): AsyncGenerator<StreamEvent, void, undefined> {
  const reader = body.getReader();
  const decoder = new TextDecoder('utf-8');
  const sse = new SSEDecoder();
  /** True once the body reported `done` — then there is nothing left to cancel. */
  let ended = false;
  const onAbort = () => {
    reader.cancel().catch(() => {});
  };
  signal?.addEventListener('abort', onAbort, { once: true });

  try {
    for (;;) {
      let chunk: ReadableStreamReadResult<Uint8Array>;
      try {
        chunk = await reader.read();
      } catch (error) {
        if (signal?.aborted || isAbortError(error)) throw new InceptionError('aborted', 'Request cancelled.', { cause: error });
        // A drop mid-answer is transient (retryable), not a refusal of the route.
        throw new InceptionError('stream', 'The connection dropped while the answer was streaming.', { cause: error });
      }
      if (signal?.aborted) throw new InceptionError('aborted', 'Request cancelled.');
      if (chunk.done) {
        ended = true;
        break;
      }

      for (const payload of sse.push(decoder.decode(chunk.value, { stream: true }))) {
        const event = parseStreamPayload(payload);
        if (!event) continue;
        if (event.type === 'done') return; // finally{} releases the connection
        yield event;
      }
    }

    for (const payload of [...sse.push(decoder.decode()), ...sse.flush()]) {
      const event = parseStreamPayload(payload);
      if (!event || event.type === 'done') continue;
      yield event;
    }
  } finally {
    signal?.removeEventListener('abort', onAbort);
    if (!ended) reader.cancel().catch(() => {});
    try {
      reader.releaseLock();
    } catch {
      // already released
    }
  }
}

function throwIfAborted(signal?: AbortSignal): void {
  if (signal?.aborted) throw new InceptionError('aborted', 'Request cancelled.');
}

function discard(res: Response): void {
  res.body?.cancel().catch(() => {});
}

function hostOf(url: string): string {
  try {
    return new URL(url).host;
  } catch {
    return url;
  }
}
